version: '2'

services:
# === FUNCTIONAL ===
  fetchhandler:
    image: fetchhandler:latest
    container_name: fetch-handler
    environment:
      - "ELASTIC_HOST=${HOST_IP}"
      - "ELASTIC_PORT=9200"
      - "CASSANDRA_HOST=${HOST_IP}"
      - "CASSANDRA_PORT=9042"
      - "KAFKA_HOST=${HOST_IP}"
      - "KAFKA_PORT=9092"
    volumes:
      - "./docker/java-filebeat/config/:/etc/filebeat"
    depends_on:
      - elastic
      - kafka
      - cassandra



# === INFRASTRUCTURE ===

  cassandra:
    build: docker/cassandra
    image: local/cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - "CASSANDRA_BROADCAST_ADDRESS:${HOST_IP}"
#      - "CASSANDRA_LISTEN_ADDRESS:"
#      - "CASSANDRA_RPC_ADDRESS:0.0.0.0"
#      - "CASSANDRA_START_RPC:"
#      - "CASSANDRA_SEEDS:"
#      - "CASSANDRA_CLUSTER_NAME:"
#      - "CASSANDRA_NUM_TOKENS:"
#      - "CASSANDRA_DC:"
#      - "CASSANDRA_RACK:"
#      - "CASSANDRA_ENDPOINT_SNITCH:"
    volumes:
      - "./docker/cassandra/data:/var/lib/cassandra"

  elastic:
    build: docker/elastic
    image: local/elastic:latest
    container_name: elastic
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "PUBLISH_IP=${HOST_IP}"
    volumes:
      - "./docker/elastic/config:/usr/share/elasticsearch/config"

  kafka:
    build: docker/kafka
    image: local/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - "KAFKA_ADVERTISED_HOST_NAME=${HOST_IP}"
      - "KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181"
#      - "KAFKA_MESSAGE_MAX_BYTES:2000000"
#      - "KAFKA_AUTO_CREATE_TOPICS_ENABLE:true"
      - "ELASTICSEARCH_URL=http://${HOST_IP}:9200"
    depends_on:
      - elastic
      - zookeeper
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  kibana:
    build: docker/kibana
    image: local/kibana:latest
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - "ELASTICSEARCH_URL=http://${HOST_IP}:9200"
    depends_on:
      - elastic

  zookeeper:
    build: docker/zookeeper
    image: local/zookeeper:latest
    container_name: zookeeper
    restart: always
    ports:  # Exposed by the base image, here for documentation more than anything else
      - "2181:2181" # Client port
      - "2888:2888" # Follower port
      - "3888:3888" # Election port
    environment:
      - "ZOO_MY_ID: 1" # Unique identifier between 1 and 255, really only used when running multiple instances
      - "ELASTICSEARCH_URL=http://${HOST_IP}:9200"
    depends_on:
      - elastic