network.host: 0.0.0.0
network.bind_host: 0.0.0.0

# Disable security
#xpack.security.enabled: false

network.publish_host: "${PUBLISH_IP}"

# this value is required because we set "network.host"
# be sure to modify it appropriately for a production cluster deployment
discovery.zen.minimum_master_nodes: 1

discovery.zen.ping.unicast.hosts: ["${PUBLISH_IP}"]
